### ISSUE TITLE
Location endpoint raises internal server error when default translation is not public

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2097]
### Describe the Bug

When a region creates a location which is a draft in the default language, but public in other languages, the location API returns an internal server error

### Steps to Reproduce

1. Create location as draft in default language
2. Publish location in different language
3. Access location API (e.g. https://admin.integreat-app.de/api/maintal/en/locations/)

### Expected Behavior

1. It should not be possible to publish a POI translation in a different language when the default translation is not public
2. In case this inconsistent state is reached anyway, the API should not deliver those POIs.

### Actual Behavior

The database inconsistency causes an internal server error

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
Feb 23 15:52:35 ERROR   django.request - 500 Internal Server Error: /maintal/en/wp-json/extensions/v3/locations/?on_map=1
Traceback (most recent call last):
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/decorators.py", line 124, in wrap
    return function(request, *args, **kwargs)
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/locations.py", line 149, in locations
    result.append(transform_poi_translation(translation))
  File "/opt/integreat-cms/.venv/lib/python3.9/site-packages/integreat_cms/api/v3/locations.py", line 75, in transform_poi_translation
    "title": poi.default_public_translation.title,
AttributeError: 'NoneType' object has no attribute 'title'
  ```

</details>

This is a regression from 70630ff7441bac673aeccde0a81e1d98e1d4ad49 (#2057).
